# These are supported funding model platforms

github: [x0lg0n, janvi100104] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: x0lg0n # Replace with a single Patreon username
ko_fi: x0lg0n # Replace with a single Ko-fi username
community_bridge: x0lg0n # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: x0lg0n # Replace with a single Liberapay username