# These are supported funding model platforms

github: [x0lg0n, janvi100104] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: x0lg0n # Replace with a single Patreon username
open_collective: x0lg0n # Replace with a single Open Collective username
ko_fi: x0lg0n # Replace with a single Ko-fi username
tidelift: x0lg0n # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: x0lg0n # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: x0lg0n # Replace with a single Liberapay username
issuehunt: x0lg0n # Replace with a single IssueHunt username
otechie: x0lg0n # Replace with a single Otechie username
lfx_crowdfunding: x0lg0n # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']